### ISSUE TITLE
Code is not being sent to robot

### ISSUE THREAD

**Issue by srikarj** [Knights-Robotics/FRC-DeepSpace--6901-2019#1]
We need to run the code in debug mode to figure out of there is an internal issue with the program because it is building and deploying with no errors however the code itself is not being sent to the robot. Until this issue is fixed, any programmers needing to push code to the robot should use the very first commit.

**Comment by Knights-Robotics** [comment]
Yeah, there was an ultrasonic declaration that wasn't commented out. The latest code should work now.
